### ISSUE TITLE
"Unidentified" taxa

### ISSUE THREAD

**Issue by puppriss** [mangal-wg/mangal-datasets#16]
Hi, in several networks that I'm looking at (IDs 15, 946, 948, and others), species named in the format "Unidentified sp3 M_PL_010", of which there are many, seem to be resolved as "Cryptichthys jojettae", which is obviously wrong. 

Also, sp. "Acarina sp1 M_PL_045" (mite sp.) is resolved as "Katianira acarina" in network lundgren_olesen_2005_20020804_908. 

Maybe the automated procedure mentioned in rmangal docs https://mangal.io/doc/r/articles/rmangal.html#search-for-a-specific-taxon could be tweaked? On the other hand, it may just be a limitation of resolving names, but I mention them in case there's an obvious fix.

Cheers
Phil

**Comment by SteveViss** [comment]
Thanks for bringing these issues to our attention. We keep you informed when those issues will be fixed (next two days).

**Comment by SteveViss** [comment]
Hi @puppriss, we dropped the taxonomy for all *Unidentified spX*.  *Acarina sp* refers now to https://mangal.io/api/v2/taxonomy/8987. Thanks for noticing this and feel free to open another issue if you find anything else.
