### ISSUE TITLE
Havens_1992 taxanomy table

### ISSUE THREAD

**Issue by clementviolet** [mangal-wg/mangal-datasets#8]
Enhance taxonomy table by completing the taxa list. Assuming that if a genus is shortened, the complete genus is just above.

[Havens_sp_list.txt](https://github.com/mangal-wg/mangal-datasets/files/2912234/Havens_sp_list.txt)
[TAXCODES.txt](https://github.com/mangal-wg/mangal-datasets/files/2912235/TAXCODES.txt)

**Comment by clementviolet** [comment]
Due to the name of some species of this dataset like `T. multicrinis`, the api reject them for some reasons, there are not in the taxonomy table. So some nodes don't have taxonomy id like `#16735`. Maybe after the cleaning of the taxonomy table for this dataset, we should update/remove node without interaction ?

**Comment by SteveViss** [comment]
`T. multicrinis` appears in the taxonomy table. See: `http://poisotlab.biol.umontreal.ca/api/v2/taxonomy?q=multicrinis`. Also, just to make sure: `taxonomy_id` is not mandatory in the node table (`null` allowed), Some node could be named as `detritus` which taxonomic info doesn't apply, then no `taxonomy_id` will be provided.

**Comment by clementviolet** [comment]
Ok, but why its `taxonomy_id` does not registered in the `node` table? ([http://poisotlab.biol.umontreal.ca/api/v2/node/16735](url))

**Comment by SteveViss** [comment]
`POST` problem perhaps?
